DROP TABLE airports CASCADE CONSTRAINTS;
DROP TABLE airplanes CASCADE CONSTRAINTS;
DROP TABLE airport_lines CASCADE CONSTRAINTS;
DROP TABLE reservations CASCADE CONSTRAINTS;
DROP TABLE customers CASCADE CONSTRAINTS;
DROP TABLE airlines CASCADE CONSTRAINTS;
DROP TABLE classes CASCADE CONSTRAINTS;